# Generated by Django 3.1 on 2020-11-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20201120_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
